src/StorekeeperAssistant.Vue.WebApp/Models/ErrorViewModel.cs
using System;

namespace StorekeeperAssistant.Vue.WebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/StorekeeperAssistant.Vue.WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using StorekeeperAssistant.Vue.WebApp.Models;
using System.Diagnostics;

namespace StorekeeperAssistant.Vue.WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/StorekeeperAssistant.Vue.WebApp/Controllers/InventoryItemController.cs
using Microsoft.AspNetCore.Mvc;
using StorekeeperAssistant.Api.Models.InventoryItems;
using StorekeeperAssistant.Api.Services;
using System.Threading.Tasks;

namespace StorekeeperAssistant.Vue.WebApp.Controllers
{
    public class InventoryItemController : Controller
    {
        private readonly IInventoryItemRemoteCallService _inventoryItemRemoteCallService;

        public InventoryItemController(IInventoryItemRemoteCallService inventoryItemRemoteCallService)
        {
            _inventoryItemRemoteCallService = inventoryItemRemoteCallService;
        }

        [HttpGet("inventory-items/get")]
        public async Task<IActionResult> GetAsync(GetInventoryItemsRequest request)
        {
            var response = await _inventoryItemRemoteCallService.GetAsync(request);

            return Json(response);
        }
    }
}

src/StorekeeperAssistant.Vue.WebApp/Controllers/MovingController.cs
using Microsoft.AspNetCore.Mvc;
using StorekeeperAssistant.Api.Models.Movings;
using StorekeeperAssistant.Api.Services;
using System.Threading.Tasks;

namespace StorekeeperAssistant.Vue.WebApp.Controllers
{
    public class MovingController : Controller
    {
        private readonly IMovingRemoteCallService _movingRemoteCallService;

        public MovingController(IMovingRemoteCallService movingRemoteCallService)
        {
            _movingRemoteCallService = movingRemoteCallService;
        }

        /// <summary>
        /// Форма спискок всех перемещений
        /// </summary>
        [Route("movings")]
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Форма спискок всех перемещений
        /// </summary>
        [Route("movings/create")]
        public IActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Получить список всех перемещений и ТМЦ
        /// </summary>
        [HttpGet("movings/get")]
        public async Task<IActionResult> GetAsync(GetMovingRequest request)
        {
            var response = await _movingRemoteCallService.GetAsync(request);
            return Json(response);
        }

        /// <summary>
        /// Создать перемещение
        /// </summary>
        [HttpPost("movings/create")]
        public async Task<IActionResult> CreateAsync([FromBody]CreateMovingRequest request)
        {
            var response = await _movingRemoteCallService.CreateAsync(request);
            return Json(response);
        }

        /// <summary>
        /// Создать перемещение
        /// </summary>
        [HttpPost("movings/delete")]
        public async Task<IActionResult> DeleteAsync([FromBody] DeleteMovingRequest request)
        {
            var response = await _movingRemoteCallService.DeleteAsync(request);
            return Json(response);
        }
    }
}

src/StorekeeperAssistant.Vue.WebApp/Controllers/WarehouseController.cs
using Microsoft.AspNetCore.Mvc;
using StorekeeperAssistant.Api.Models.Warehouses;
using StorekeeperAssistant.Api.Services;
using System.Threading.Tasks;

namespace StorekeeperAssistant.Vue.WebApp.Controllers
{
    public class WarehouseController : Controller
    {
        private readonly IWarehouseRemoteCallService _warehouseRemoteCallService;

        public WarehouseController(IWarehouseRemoteCallService warehouseRemoteCallService)
        {
            _warehouseRemoteCallService = warehouseRemoteCallService;
        }

        [HttpGet("warehouses/get")]
        public async Task<IActionResult> GetAsync(GetWarehouseRequest request)
        {
            var response = await _warehouseRemoteCallService.GetAsync(request);

            return Json(response);
        }
    }
}

src/StorekeeperAssistant.Vue.WebApp/Controllers/WarehouseInventoryItemController.cs
using Microsoft.AspNetCore.Mvc;
using StorekeeperAssistant.Api.Models.WarehouseInventoryItems;
using StorekeeperAssistant.Api.Services;
using System.Threading.Tasks;

namespace StorekeeperAssistant.Vue.WebApp.Controllers
{
    public class WarehouseInventoryItemController : Controller
    {
        private readonly IWarehouseInventoryItemRemoteCallService _warehouseInventoryItemRemoteCallService;

        public WarehouseInventoryItemController(IWarehouseInventoryItemRemoteCallService warehouseInventoryItemRemoteCallService)
        {
            _warehouseInventoryItemRemoteCallService = warehouseInventoryItemRemoteCallService;
        }

        [HttpGet("warehouse-inventory-items/report")]
        public IActionResult Report()
        {
            return View();
        } 

        [HttpGet("warehouse-inventory-items/get/{WarehouseId:int}")]
        public async Task<IActionResult> GetAsync(GetWarehouseInventoryItemRequest request)
        {
            var response = await _warehouseInventoryItemRemoteCallService.GetAsync(request);

            return Json(response);
        }
    }
}

src/StorekeeperAssistant.Vue.WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Шаблон приложения Помощник кладовщика";
}

<div class="text-center">
    <p>Данный пример является показным, не полным и не несет в себе смысловой нагрузки.</p>
    GitHub: <a href="https://github.com/eddchervov/StorekeeperAssistant.ClientServer">eddchervov.StorekeeperAssistant.ClientServer</a>
</div>

src/StorekeeperAssistant.Vue.WebApp/Views/Moving/Create.cshtml
@{
    ViewData["Title"] = "Создать перемещение";
}


<div id="create-moving-app"></div>

@section Scripts {
    <script src="~/app/build/moving-create.js"></script>
}

src/StorekeeperAssistant.Vue.WebApp/Views/Moving/Index.cshtml
@{
    ViewData["Title"] = "Список перемещений";
}

<div id="list-moving-app"></div>


@section Scripts {
    <script src="~/app/build/moving-list.js"></script>
}

src/StorekeeperAssistant.Vue.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Помощник кладовщика</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true">
    <!-- CDN -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
</head>
<body>
    <header class="bg-light">
        <div class="container">
            <h5 class="mb-3 ps-2"><a href="http://eddcher.ru/">Вернуться на eddcher.ru</a></h5>
            <nav class="navbar navbar-expand-lg navbar-light mb-3">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-controller="Home" asp-action="Index">Помощник кладовщика</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Moving" asp-action="Create">Создать перемещениe</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Moving" asp-action="Index">Список перемещений</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="WarehouseInventoryItem" asp-action="Report">Отчет по остаткам</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>

    </header>
    <div class="container">
        @RenderBody()
    </div>

    <footer class="border-top footer text-muted mt-4">
        <div class="container">
            &copy; @DateTime.Now.Year - Помощник кладовщика
            <p>GitHub: <a target="_blank" href="https://github.com/eddchervov/StorekeeperAssistant.ClientServer">eddchervov.StorekeeperAssistant.ClientServer</a></p>
        </div>
    </footer>
    <!-- CDN -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

src/StorekeeperAssistant.Vue.WebApp/Views/WarehouseInventoryItem/Report.cshtml
@{
    ViewData["Title"] = "Отчет";
}

<div id="report-app"></div>


@section Scripts {
    <script src="~/app/build/report.js"></script>
}